### ISSUE TITLE
Error: '/bin/sh nextdenovo/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align0/raw_align001/nextDenovo.sh

### ISSUE THREAD

**Issue by qianqianqian0717** [Nextomics/NextDenovo#137]
Hi, Dr. Hu
I ran into this problem when I assembled the genome from ONT data and couldn't solve it:

Exception: Command '/bin/sh 01_rundir/01.raw_align/02.raw_align.sh.work/raw_align0/raw_align001/nextDenovo.sh > 01_rundir/01.raw_align/02.raw_align.sh.work/raw_align0/raw_align001/nextDenovo.sh.o 2> 01_rundir/01.raw_align/02.raw_align.sh.work/raw_align0/raw_align001/nextDenovo.sh.e' returned non-zero exit status 1, error info: .

My configuration file  run.cfg is as follows

[General]
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 6
parallel_jobs = 20
input_type = raw
read_type = ont
input_fofn = input.fofn
workdir = 01_rundir

[correct_option]
read_cutoff = 1k
genome_size = 480M
seed_cutoff = 57862
blocksize = 2g
pa_correction = 15
seed_cutfiles = 20
sort_options = -m 1g -t 10 -k 40
minimap2_options_raw = - x ava-ont -t 8
correction_options = -p 15

[assemble_option]
random_round = 20
minimap2_options_cns = -x ava-ont -t 8 -k17 -w17
nextgraph_options = -a 1

Could you give me some advice?
Thanks

**Comment by moold** [comment]
Could you paste the content of file `01_rundir/01.raw_align/02.raw_align.sh.work/raw_align0/raw_align001/nextDenovo.sh.e` to here?

**Comment by qianqianqian0717** [comment]
Hi, Dr. Hu
Here is the file:

hostname
+ hostname
cd 01_rundir/01.raw_align/02.raw_align.sh.work/raw_align0/raw_align003
+ cd 01_rundir/01.raw_align/02.raw_align.sh.work/raw_align0/raw_align003
time NextDenovo/bin/minimap2-nd --step 1 --dual=yes - x ava-ont -t 8 -x ava-ont 01_rundir/01.raw_align/input.seed.008.2bit 01_rundir/01.raw_align/input.part.017.2bit -o input.seed.008.2bit.2.ovl;
+ NextDenovo/bin/minimap2-nd --step 1 --dual=yes - x ava-ont -t 8 -x ava-ont 01_rundir/01.raw_align/input.seed.008.2bit 01_rundir/01.raw_align/input.part.017.2bit -o input.seed.008.2bit.2.ovl
[ERROR] failed to find seq file type or empty file

real    0m0.702s
user    0m0.468s
sys     0m0.211s

**Comment by moold** [comment]
As the log says, the input files `01_rundir/01.raw_align/input.seed.008.2bit` or `01_rundir/01.raw_align/input.part.017.2bit` is empty, so pls check your input `input_fofn ` and the log file in `01_rundir/01.raw_align/02.db_split.sh.work/db_split1/nextDenovo.sh.e`

**Comment by qianqianqian0717** [comment]
Hi, Dr. Hu
I have checked my input_fofn file and log file, input_fofn file only contains the path of the ONT data in fastq.gz format, and the error in the log file is the same as above. Beyond that, the input files 01_rundir/01.raw_align/input.seed.008.2bit was also checked and found to be 224M.

**Comment by moold** [comment]
How about `01_rundir/01.raw_align/input.part.017.2bit` ?

**Comment by qianqianqian0717** [comment]
Its file size is also 224MB

**Comment by moold** [comment]
Try to reinstall the lastest version of NextDenovo and rerun from the beginning.

**Comment by hafizmtalha** [comment]
Hi Dr. 
M facing the similar error:

command '/bin/sh /home/navi/magnaporthe-KI215/assembly_number_3/01.raw_align/03.raw_align.sh.work/raw_align08/nextDenovo.sh > /home/navi/magnaporthe-KI215/assembly_number_3/01.raw_align/03.raw_align.sh.work/raw_align08/nextDenovo.sh.o 2> /home/navi/magnaporthe-KI215/assembly_number_3/01.raw_align/03.raw_align.sh.work/raw_align08/nextDenovo.sh.e' returned non-zero exit status 137, error info: .
Traceback (most recent call last):
  File "./nextDenovo", line 850, in <module>
    main(args)
  File "./nextDenovo", line 648, in main
    task.run.start()
  File "/home/navi/.local/lib/python3.8/site-packages/paralleltask/task_control.py", line 344, in start
    self._start()
  File "/home/navi/.local/lib/python3.8/site-packages/paralleltask/task_control.py", line 368, in _start
    self.submit(job)
  File "/home/navi/.local/lib/python3.8/site-packages/paralleltask/task_control.py", line 252, in submit
    _, stdout, _ = self.run(job.cmd)
  File "/home/navi/.local/lib/python3.8/site-packages/paralleltask/task_control.py", line 288, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/usr/lib/python3.8/logging/__init__.py", line 1493, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.8/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.8/logging/__init__.py", line 954, in handle
    self.emit(record)
  File "/home/navi/.local/lib/python3.8/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/sh /home/navi/magnaporthe-KI215/assembly_number_3/01.raw_align/03.raw_align.sh.work/raw_align08/nextDenovo.sh > /home/navi/magnaporthe-KI215/assembly_number_3/01.raw_align/03.raw_align.sh.work/raw_align08/nextDenovo.sh.o 2> /home/navi/magnaporthe-KI215/assembly_number_3/01.raw_align/03.raw_align.sh.work/raw_align08/nextDenovo.sh.e' returned non-zero exit status 137, error info: .

raw_align08/nextDenovo.sh.e files has the following error

hostname
+ hostname
cd /home/navi/magnaporthe-KI215/assembly_number_3/01.raw_align/03.raw_align.sh.work/raw_align08
+ cd /home/navi/magnaporthe-KI215/assembly_number_3/01.raw_align/03.raw_align.sh.work/raw_align08
time /home/navi/magnaporthe-KI215/NextDenovo/bin/minimap2-nd --step 1 -I 3G --dual=yes -t 5 -x ava-ont /home/navi/magnaporthe-KI215/NextDenovo/../assembly_number_3/01.raw_align/input.seed.001.2bit /home/navi/magnaporthe-KI215/NextDenovo/../assembly_number_3/01.raw_align/input.seed.003.2bit -o input.seed.001.2bit.4.ovl;ln -sf input.seed.001.2bit.4.ovl input.seed.003.2bit.4.ovl;
+ time /home/navi/magnaporthe-KI215/NextDenovo/bin/minimap2-nd --step 1 -I 3G --dual=yes -t 5 -x ava-ont /home/navi/magnaporthe-KI215/NextDenovo/../assembly_number_3/01.raw_align/input.seed.001.2bit /home/navi/magnaporthe-KI215/NextDenovo/../assembly_number_3/01.raw_align/input.seed.003.2bit -o input.seed.001.2bit.4.ovl
[M::mm_idx_gen::14.331*1.71] collected minimizers
[M::mm_idx_gen::18.664*2.03] sorted minimizers
[M::main::18.664*2.03] loaded/built the index for 17850 target sequence(s)
[M::mm_mapopt_update::19.747*1.97] mid_occ = 439
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 17850
[M::mm_idx_stat::20.756*1.90] distinct minimizers: 63051508 (63.44% are singletons); average occurrences: 3.650; average spacing: 2.932
Command terminated by signal 9
288.60user 7.99system 1:35.15elapsed 311%CPU (0avgtext+0avgdata 6486324maxresident)k
488384inputs+24outputs (719major+3395948minor)pagefaults 0swaps

**Comment by moold** [comment]
It seems you don't have enough memory, try to reduce`parallel_jobs` and `pa_correction`
