### ISSUE TITLE
 db_stat failed

### ISSUE THREAD

**Issue by alexvasilikop** [Nextomics/NextDenovo#158]
**Describe the bug**
Hello, running nextdenovo on my PacBio HiFi dataset using the following configuration file

gives the following error message:
nextDenovo Rotaria_rotatoria.inputHiFi.conf --log Rotaria_rotatoria.inputHiFi.conf.log
[17184 INFO] 2022-12-15 10:00:59 NextDenovo start...
[17184 INFO] 2022-12-15 10:00:59 version:v2.5.0 logfile:pid17184.Rotaria_rotatoria.inputHiFi.conf.log
[17184 WARNING] 2022-12-15 10:00:59 Re-write workdir
[17184 WARNING] 2022-12-15 10:00:59 Change task "all" to "assemble", becasue the input_type is "corrected"
[17184 INFO] 2022-12-15 10:00:59 skip mkdir: /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir
[17184 INFO] 2022-12-15 10:00:59 skip mkdir: /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align
[17184 INFO] 2022-12-15 10:00:59 skip mkdir: /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/02.cns_align
[17184 INFO] 2022-12-15 10:00:59 skip mkdir: /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/03.ctg_graph
[17184 INFO] 2022-12-15 10:01:04 Total jobs: 1
[17184 INFO] 2022-12-15 10:01:04 Submitted jobID:[17185] jobCmd:[/mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh] in the local_cycle.
[17185 CRITICAL] 2022-12-15 10:01:04 Command '/bin/sh /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh > /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.o 2> /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.e' returned non-zero exit status 1, error info: .
Traceback (most recent call last):
  File "/mnt/sdc1/Alex/software/NextDenovo/nextDenovo", line 850, in <module>
    main(args)
  File "/mnt/sdc1/Alex/software/NextDenovo/nextDenovo", line 594, in main
    task.run.start()
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/site-packages/paralleltask/task_control.py", line 347, in start
    self._start()
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/site-packages/paralleltask/task_control.py", line 371, in _start
    self.submit(job)
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/site-packages/paralleltask/task_control.py", line 255, in submit
    _, stdout, _ = self.run(job.cmd)
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/site-packages/paralleltask/task_control.py", line 291, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/logging/__init__.py", line 1219, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/home/lege/anaconda3/envs/nextomics/lib/python2.7/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/sh /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh > /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.o 2> /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.e' returned non-zero exit status 1, error info: .
[17184 ERROR] 2022-12-15 10:01:10 db_stat failed: please check the following logs:
[17184 ERROR] 2022-12-15 10:01:10 /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.e

Content of nextDenovo.sh.e:
hostname
hostname
cd /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1
cd /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/01.db_stat.sh.work/db_stat1
time /mnt/sdc1/Alex/software/NextDenovo/bin/seq_stat -f 10k -g 180m -d 30 -a -o /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/input.reads.stat /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.inputHiFi.fofn
time /mnt/sdc1/Alex/software/NextDenovo/bin/seq_stat -f 10k -g 180m -d 30 -a -o /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.all_reads.workdir/01.raw_align/input.reads.stat /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.inputHiFi.fofn
Error! /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/02.FILTLONG/Rotaria_rotatoria.PacBio_HiFi.m64279e_221025_110133.fastq.gz does not exist!Command exited with non-zero status 1
0.00user 0.00system 0:00.00elapsed 0%CPU (0avgtext+0avgdata 1932maxresident)k
0inputs+0outputs (0major+80minor)pagefaults 0swaps

**Genome characteristics**
The genome size should be aroung 180-200Mb (haploid) although we are not sure

**Input data**
The input length distribution is the following
Types            Count (#) Length (bp)
N10                   6415   14208
N20                  13658   13204
N30                  21350   12547
N40                  29407   12028
N50                  37786   11589
N60                  46465   11210
N70                  55425   10875
N80                  64655   10562
N90                  74151   10270

Types               Count (#)           Bases (bp)  Depth (X)
Raw                     83911            989053808       4.95
Filtered                    0                    0       0.00
Clean                   83911            989053808       4.95

**Config file**
[General]

job_type = local
job_prefix = nextDenovo
task = all
rewrite = yes
deltmp = yes
rerun = 3
parallel_jobs = 10
input_type = raw
input_fofn = Rotaria_rotatoria.inputHiFi.10000.90.fofn
workdir = /mnt/sdc1/Alex/Rotaria_rotatoria_assembly/03.NextDenovo/Rotaria_rotatoria.ND.10000.90.workdir
[correct_option]
read_cutoff = 10k
seed_cutoff = 10001
seed_depth = 45 
read_type=hifi
genome_size = 200M # estimated genome size
blocksize = 1g
pa_correction = 10
seed_cutfiles = 2
sort_options = -m 5g -t 2 -k 40
minimap2_options_raw = -x ava-hifi -t 2
correction_options = -p 15
[assemble_option]
random_round = 10
minimap2_options_cns = -x ava-hifi -t 2 -k17 -w17
nextgraph_options = -a 1

**Operating system**
Distributor ID:	Ubuntu
Description:	Ubuntu 18.10
Release:	18.10
Codename:	cosmic

**GCC**
gcc version 8.3.0 (Ubuntu 8.3.0-6ubuntu1~18.10.1) 

**Python**
Python 2.7.15

**NextDenovo**
nextDenovo v2.5.0

Any help would be appreciated thanks
Alex

**Comment by alexvasilikop** [comment]
Input reads file was in a different path so issue closed
