### ISSUE TITLE
Unable to run NextDeVovo  on the test data

### ISSUE THREAD

**Issue by hermonieg11** [Nextomics/NextDenovo#161]
**Describe the bug**
I am trying to teach myself how to use NextDenovo. I follow the instructions on the installation guide and when I run the test data, it immediately runs into an error. I tried downloading the tutorial data as well and get the same error. I'm not sure what's happening that I can't run the code on even the test data that was supplied with it. Thanks in advance for your help!

**Error message**
blackmonlab@blackmonlab-M-CLASS:~/Desktop/Priscilla/NextDenovo$ ./nextDenovo test_data/run.cfg py -3
[54320 INFO] 2023-01-27 11:46:55 NextDenovo start...
[54320 INFO] 2023-01-27 11:46:55 version:v2.5.0 logfile:pid54320.log.info
[54320 WARNING] 2023-01-27 11:46:55 Re-write workdir
[54320 INFO] 2023-01-27 11:46:55 skip mkdir: /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/./01_rundir
[54320 INFO] 2023-01-27 11:46:55 skip mkdir: /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/./01_rundir/01.raw_align
[54320 INFO] 2023-01-27 11:46:55 skip mkdir: /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/./01_rundir/02.cns_align
[54320 INFO] 2023-01-27 11:46:55 skip mkdir: /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/./01_rundir/03.ctg_graph
[54320 INFO] 2023-01-27 11:47:00 Total jobs: 1
[54320 INFO] 2023-01-27 11:47:00 Submitted jobID:[54321] jobCmd:[/home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh] in the local_cycle.
[54321 CRITICAL] 2023-01-27 11:47:00 Command '/bin/sh /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh > /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.o 2> /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.e' returned non-zero exit status 2, error info: .
Traceback (most recent call last):
  File "./nextDenovo", line 850, in <module>
    main(args)
  File "./nextDenovo", line 594, in main
    task.run.start()
  File "/home/blackmonlab/.local/lib/python2.7/site-packages/paralleltask/task_control.py", line 348, in start
    self._start()
  File "/home/blackmonlab/.local/lib/python2.7/site-packages/paralleltask/task_control.py", line 372, in _start
    self.submit(job)
  File "/home/blackmonlab/.local/lib/python2.7/site-packages/paralleltask/task_control.py", line 252, in submit
    _, stdout, _ = self.run(job.cmd)
  File "/home/blackmonlab/.local/lib/python2.7/site-packages/paralleltask/task_control.py", line 292, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/usr/lib/python2.7/logging/__init__.py", line 1219, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1293, in _log
    self.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1303, in handle
    self.callHandlers(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 1343, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python2.7/logging/__init__.py", line 766, in handle
    self.emit(record)
  File "/home/blackmonlab/.local/lib/python2.7/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/sh /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh > /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.o 2> /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.e' returned non-zero exit status 2, error info: .
[54320 ERROR] 2023-01-27 11:47:06 db_stat failed: please check the following logs:
[54320 ERROR] 2023-01-27 11:47:06 /home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh.e

When I open this file, it says: 
/home/blackmonlab/Desktop/Priscilla/NextDenovo/test_data/01_rundir/01.raw_align/01.db_stat.sh.work/db_stat1/nextDenovo.sh: 2: set: Illegal option -o pipefail

**Genome characteristics**
original test_data

**Input data**
o.g. test data file

**Config file**
[General]
job_type = local
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 2
input_type = raw
read_type = clr
input_fofn = ./input.fofn
workdir = ./01_rundir

[correct_option]
read_cutoff = 1k
genome_size = 308161
pa_correction = 2
sort_options = -m 1g -t 2
minimap2_options_raw =  -t 8
correction_options = -p 15

[assemble_option]
minimap2_options_cns =  -t 8
nextgraph_options = -a 1

**Operating system**
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic

**GCC**
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1 ~18.04 ' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04) 

**Python**
Python 2.7.17

**NextDenovo**
What version of NextDenovo are you using?
nextDenovo v2.5.0

**To Reproduce** (Optional)
Steps to reproduce the behavior. Providing a minimal test dataset on which we can reproduce the behavior will generally lead to quicker turnaround time!

**Additional context** (Optional)
I tried using python 3 as well with no luck in moving past this error

**Comment by moold** [comment]
Hi，I have fixed this bug, try `pip install --upgrade paralleltask` to update `paralleltask`

**Comment by hermonieg11** [comment]
Thank you!
