### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by taotaoyuan** [Nextomics/NextDenovo#163]
Here is my run.cfg file.
[General]
job_type = local # local, slurm, sge, pbs, lsf
job_prefix = nextDenovo
task = assemble # all, correct, assemble
rewrite = yes # yes/no
deltmp = yes
parallel_jobs = 10 # number of tasks used to run in parallel
input_type = corrected # raw, corrected
read_type = hifi # clr, ont, hifi
input_fofn = ./input.fofn
workdir = 0204-nextdenovo

[correct_option]
read_cutoff = 1k
genome_size = 5m # estimated genome size
seed_cutoff = 5k
sort_options = -m 50g -t 30
minimap2_options_raw = -x ava-hifi -t 30
pa_correction = 5 # number of corrected tasks used to run in parallel, each corrected task requires ~TOTAL_INPUT_BASES/4 bytes of memory usage.
correction_options = -p 30

[assemble_option]
minimap2_options_cns = -x ava-hifi -t 32
nextgraph_options = -a 1

I encountered this error when I ran nextdenovo to assemble the hifi data.

```
[7714 INFO] 2023-02-04 21:34:43 remove temporary result: /home/lx_sky6/yt/20230106_baimaike/0105_YC_hifi/BMK220921-BB398-02P0001/cell/mito/0204-nextdenovo/03.ctg_graph/02.ctg_align.sh.work/ctg_align3/cns1.fasta.sort.bam
[7714 INFO] 2023-02-04 21:34:43 remove temporary result: /home/lx_sky6/yt/20230106_baimaike/0105_YC_hifi/BMK220921-BB398-02P0001/cell/mito/0204-nextdenovo/03.ctg_graph/02.ctg_align.sh.work/ctg_align4/cns4.fasta.sort.bam
[7714 INFO] 2023-02-04 21:34:43 remove temporary result: /home/lx_sky6/yt/20230106_baimaike/0105_YC_hifi/BMK220921-BB398-02P0001/cell/mito/0204-nextdenovo/03.ctg_graph/02.ctg_align.sh.work/ctg_align5/cns3.fasta.sort.bam
Traceback (most recent call last):
  File "/home/lx_sky6/software/NextDenovo/nextDenovo", line 850, in <module>
    main(args)
  File "/home/lx_sky6/software/NextDenovo/nextDenovo", line 821, in main
    asm, stat = gather_ctg_cns_output(cfg, task.jobs, seq_info)
  File "/home/lx_sky6/software/NextDenovo/nextDenovo", line 293, in gather_ctg_cns_output
    out = cal_n50_info(stat, asm + '.stat')
  File "/home/lx_sky6/software/NextDenovo/lib/kit.py", line 204, in cal_n50_info
    out += "%-5s %18d%20s\n" % ("Min.", stat[-1], '-')
IndexError: list index out of range
[6754 INFO] 2023-02-04 21:36:50 split_seed done
[6754 INFO] 2023-02-04 21:36:51 Total jobs: 15
[6754 INFO] 2023-02-04 21:36:51 Submitted jobID:[40458] jobCmd:[/home/lx_sky6/yt/20230106_baimaike/0105_YC_hifi/mito/0202-nextdenovo/02.cns_align/02.cns_align.sh.work/cns_align01/nextDenovo.sh] in the pbs_cycle.
```

[nohup.out.zip](https://github.com/Nextomics/NextDenovo/files/10608752/nohup.out.zip)

**Comment by moold** [comment]
Hi，Nextdenovo is not optimized for hifi data, so it is not suitable for hifi data by now, so...
