### ISSUE TITLE
TypeError: unsupported operand type(s)

### ISSUE THREAD

**Issue by ianaebutler** [Nextomics/NextDenovo#179]
**Describe the bug**
I am trying to run some Oxford Nanopore data and I am getting the following error message. 
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Error message**
<pre>
[1429643 INFO] 2023-06-01 10:59:19 NextDenovo start...
[1429643 INFO] 2023-06-01 10:59:19 version:2.5.2 logfile:pid1429643.log.info
[1429643 WARNING] 2023-06-01 10:59:19 Re-write workdir
[1429643 INFO] 2023-06-01 10:59:19 skip mkdir: /home/ianbutler/NextDenovo/./
[1429643 INFO] 2023-06-01 10:59:19 mkdir: /home/ianbutler/NextDenovo/.//01.raw_align
[1429643 INFO] 2023-06-01 10:59:19 mkdir: /home/ianbutler/NextDenovo/.//02.cns_align
[1429643 INFO] 2023-06-01 10:59:19 mkdir: /home/ianbutler/NextDenovo/.//03.ctg_graph
</pre>

And here is the traceback that has a bit more information
<pre>
Traceback (most recent call last):
  File "./nextDenovo", line 857, in <module>
    main(args)
  File "./nextDenovo", line 595, in main
    task.set_run(max_parallel_job=1, job_type=cfg['job_type'], use_drmaa=cfg['use_drmaa'], \
  File "/usr/local/lib/python3.8/dist-packages/paralleltask/task_control.py", line 175, in set_run
    self.run = Cluster(self.jobs, max_parallel_job, self.shell, job_type, interval_time, \
  File "/usr/local/lib/python3.8/dist-packages/paralleltask/task_control.py", line 202, in __init__
    self.mem = self._parse_mem(str(mem))
  File "/usr/local/lib/python3.8/dist-packages/paralleltask/task_control.py", line 239, in _parse_mem
    unit_cfg_fpath = os.getenv('LSF_ENVDIR') + "/lsf.conf"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
</pre>

**Genome characteristics**
Genome is about 200Mb. Not sure about other things

**Input data**
Number of bases: 188433154
mean read length: 1240
median read length: 563
N50: 2629

**Config file**
<pre>
[General]
job_type = lsf
job_prefix = nextDenovo
task = all # 'all', 'correct', 'assemble'
rewrite = yes # yes/no
deltmp = yes
rerun = 3
parallel_jobs = 2
input_type = raw
read_type = ont
input_fofn = ./CNIN4784input.fofn
workdir = ./

[correct_option]
read_cutoff = 1k
genome_size = 200m
pa_correction = 2
sort_options = -m 1g -t 2
minimap2_options_raw =  -t 8
correction_options = -p 15

[assemble_option]
minimap2_options_cns =  -t 8
nextgraph_options = -a 1
</pre>

**Operating system**
Ubuntu 20.04.4 LTS

**GCC**
gcc version 9.4.0

**Python**
Python 3.8.10

**NextDenovo**
nextDenovo 2.5.2

**Comment by moold** [comment]
you can try to set `job_type = local` or see [here](https://www.ibm.com/docs/en/spectrum-lsf/10.1.0?topic=lsfconf-lsf-envdir) to set the environment variable: `LSF_ENVDIR` .

**Comment by ianaebutler** [comment]
Setting <code>job_type = local</code> solved the problem. Thanks
