### ISSUE TITLE
Running out of disk space

### ISSUE THREAD

**Issue by oskesr** [Nextomics/NextDenovo#212]
**Describe the bug**
The SSD with the working directory has 1.1TB free. Over time, it fill up and there is 0 bytes remaining. Program doesnt give error but has no updates in status.

**System**
Pop!_OS 22.04 LTS
128 threads, 512GB RAM

**GCC**
gcc version 11.4.0 (Ubuntu 11.4.0-1ubuntu1~22.04) 

**Python**
3.11.5

**NextDenovo**
2.5.2

**pid.log.info**

[20841 INFO] 2024-06-11 14:17:52 NextDenovo start...
[20841 INFO] 2024-06-11 14:17:52 version:2.5.2 logfile:pid20841.log.info
[20841 WARNING] 2024-06-11 14:17:52 Re-write workdir
[20841 INFO] 2024-06-11 14:17:52 skip mkdir: /out_nextden_v2/01_rundir
[20841 INFO] 2024-06-11 14:17:52 skip mkdir: /out_nextden_v2/01_rundir/01.raw_align
[20841 INFO] 2024-06-11 14:17:52 skip mkdir: /out_nextden_v2/01_rundir/02.cns_align
[20841 INFO] 2024-06-11 14:17:52 skip mkdir: /out_nextden_v2/01_rundir/03.ctg_graph
[20841 INFO] 2024-06-11 14:17:52 skip step: db_stat
[20841 INFO] 2024-06-11 14:17:52 updated options:
rerun:                        3
task:                         all
deltmp:                       1
rewrite:                      1
read_type:                    ont
job_type:                     local
input_type:                   raw
read_cutoff:                  1k
genome_size:                  1g
parallel_jobs:                6
seed_depth:                   45.0
pa_correction:                3
seed_cutfiles:                3
seed_cutoff:                  21711
blocksize:                    12538658079
ctg_cns_options:              -p 20
nextgraph_options:            -a 1
job_prefix:                   nextDenovoDupAll
sort_options:                 -m 60g -t 20 -k 40
minimap2_options_map:         -x map-ont
minimap2_options_raw:         -x ava-ont -t 8 --minlen 1000
workdir:                      /out_nextden_v2/01_rundir
input_fofn:                   /out_nextden_v2/input.fofn
correction_options:           -p 20 -max_lq_length 10000 -r ont -min_len_seed 10855
minimap2_options_cns:         -t 8 -x ava-ont -k 17 -w 17 --minlen 2000 --maxhan1 5000
raw_aligndir:                 /out_nextden_v2/01_rundir/01.raw_align
cns_aligndir:                 /out_nextden_v2/01_rundir/02.cns_align
ctg_graphdir:                 /out_nextden_v2/01_rundir/03.ctg_graph
[20841 INFO] 2024-06-11 14:17:52 summary of input data:
file: /out_nextden_v2/01_rundir/01.raw_align/input.reads.stat 
[Read length stat]
Types            Count (#) Length (bp)
N10                 129480   58658
N20                 316017   44887
N30                 557075   34866
N40                 869037   26753
N50                1280672   19998
N60                1841548   14425
N70                2638736    9881
N80                3868666    5984
N90                6101275    3592

Types               Count (#)           Bases (bp)  Depth (X)
Raw                  11969839          96270451854      96.27
Filtered              2218410           1119819538       1.12
Clean                 9751429          95150632316      95.15

*Suggested seed_cutoff (genome size: 1000.00Mb, expected seed depth: 45, real seed depth: 45.00): 21711 bp
[20841 INFO] 2024-06-11 14:17:52 skip step: db_split
[20841 INFO] 2024-06-11 14:17:52 Total jobs: 18
[20841 INFO] 2024-06-11 14:17:52 Submitted jobID:[20842] jobCmd:[/out_nextden_v2/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align01/nextDenovoDupAll.sh] in the local_cycle.
[20841 INFO] 2024-06-11 14:17:53 Submitted jobID:[20848] jobCmd:[/out_nextden_v2/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align02/nextDenovoDupAll.sh] in the local_cycle.
[20841 INFO] 2024-06-11 14:17:53 Submitted jobID:[20857] jobCmd:[/out_nextden_v2/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align03/nextDenovoDupAll.sh] in the local_cycle.
[20841 INFO] 2024-06-11 14:17:54 Submitted jobID:[20866] jobCmd:[/out_nextden_v2/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align04/nextDenovoDupAll.sh] in the local_cycle.
[20841 INFO] 2024-06-11 14:17:54 Submitted jobID:[20875] jobCmd:[/out_nextden_v2/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align05/nextDenovoDupAll.sh] in the local_cycle.
[20841 INFO] 2024-06-11 14:17:55 Submitted jobID:[20884] jobCmd:[/out_nextden_v2/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align06/nextDenovoDupAll.sh] in the local_cycle.
[20841 INFO] 2024-06-13 07:28:22 Submitted jobID:[825257] jobCmd:[/out_nextden_v2/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align07/nextDenovoDupAll.sh] in the local_cycle.

**Config file**
[General]
job_type = local # local, slurm, sge, pbs, lsf
job_prefix = nextDenovoDupAll
task = all # all, correct, assemble
rewrite = yes # yes/no
deltmp = yes 
parallel_jobs = 6 # number of tasks used to run in parallel
input_type = raw # raw, corrected
read_type = ont # clr, ont, hifi
input_fofn = input.fofn
workdir = 01_rundir

[correct_option]
read_cutoff = 1k
genome_size = 1g # estimated genome size
sort_options = -m 60g -t 20
minimap2_options_raw = -x ava-ont -t 8 --minlen 1000
pa_correction = 3 # number of corrected tasks used to run in parallel, each corrected task requires ~TOTAL_INPUT_BASES/4 bytes of memory usage.
correction_options = -p 20

[assemble_option]
minimap2_options_cns = -t 8 
nextgraph_options = -a 1

**Comment by moold** [comment]
No other solution except to increase the working directory storage.

**Comment by oskesr** [comment]
Thanks for the clarification, could you suggest what size could be needed?
If there was an estimate such as for x bases you need 2x storage ?

Additionally, would you reccommend any changes in the parameters for utilizing the threads more effectively ?

**Comment by moold** [comment]
1. Normally, 1T of storage is sufficient to assemble a 1G genome, but the actual size depends on the genome's repetitive sequence content and the input bases. SO it is hard to say.
2. See [here](https://nextdenovo.readthedocs.io/en/latest/FAQ.html#id2) to optimize parallel computing parameters.

**Comment by oskesr** [comment]
Hello @moold, so I have started the run on a new 5TB drive, and it is again filled up 100%.
But this time I have an error, what do you think ?

```
*Suggested seed_cutoff (genome size: 1000.00Mb, expected seed depth: 45, real seed depth: 45.00): 21711 bp
[34267 INFO] 2024-07-01 15:38:50 Total jobs: 1
[34267 INFO] 2024-07-01 15:38:50 Submitted jobID:[34268] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/02.db_split.sh.work/db_split1/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-01 15:52:34 db_split done
[34267 INFO] 2024-07-01 15:52:34 Total jobs: 18
[34267 INFO] 2024-07-01 15:52:34 Submitted jobID:[38429] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align01/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-01 15:52:35 Submitted jobID:[38435] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align02/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-01 15:52:35 Submitted jobID:[38444] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align03/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-01 15:52:36 Submitted jobID:[38453] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align04/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-01 15:52:36 Submitted jobID:[38462] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align05/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-01 15:52:37 Submitted jobID:[38471] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align06/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-02 21:48:24 Submitted jobID:[863498] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align07/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-04 01:03:44 Submitted jobID:[1392823] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align08/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-04 01:29:03 Submitted jobID:[1401051] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align09/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-04 02:36:35 Submitted jobID:[1463595] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align10/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-04 02:57:47 Submitted jobID:[1470951] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align11/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-04 03:42:46 Submitted jobID:[1487070] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align12/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-05 06:56:02 Submitted jobID:[2001943] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align13/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-05 09:07:31 Submitted jobID:[2037533] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align14/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-06 12:44:37 Submitted jobID:[4077104] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align15/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-06 12:44:52 Submitted jobID:[4077398] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align16/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-06 13:26:48 Submitted jobID:[4127743] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align17/nextDenovoDupAll.sh] in the local_cycle.
[34267 INFO] 2024-07-06 14:37:46 Submitted jobID:[28556] jobCmd:[/mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align18/nextDenovoDupAll.sh] in the local_cycle.
[28556 CRITICAL] 2024-07-07 20:06:07 Command '/bin/bash /mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align18/nextDenovoDupAll.sh > /mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align18/nextDenovoDupAll.sh.o 2> /mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align18/nextDenovoDupAll.sh.e' returned non-zero exit status 1, error info: .
Traceback (most recent call last):
  File "/mnt/gcfgrandmaison/T07_sesu/out_nextden/../NextDenovo/nextDenovo", line 857, in <module>
    main(args)
  File "/mnt/gcfgrandmaison/T07_sesu/out_nextden/../NextDenovo/nextDenovo", line 651, in main
    task.run.start()
  File "/home/omk/minicondanew/lib/python3.11/site-packages/paralleltask/task_control.py", line 350, in start
    self._start()
  File "/home/omk/minicondanew/lib/python3.11/site-packages/paralleltask/task_control.py", line 374, in _start
    self.submit(job)
  File "/home/omk/minicondanew/lib/python3.11/site-packages/paralleltask/task_control.py", line 254, in submit
    _, stdout, _ = self.run(job.cmd)
                   ^^^^^^^^^^^^^^^^^
  File "/home/omk/minicondanew/lib/python3.11/site-packages/paralleltask/task_control.py", line 294, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/home/omk/minicondanew/lib/python3.11/logging/__init__.py", line 1536, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/home/omk/minicondanew/lib/python3.11/logging/__init__.py", line 1634, in _log
    self.handle(record)
  File "/home/omk/minicondanew/lib/python3.11/logging/__init__.py", line 1644, in handle
    self.callHandlers(record)
  File "/home/omk/minicondanew/lib/python3.11/logging/__init__.py", line 1706, in callHandlers
    hdlr.handle(record)
  File "/home/omk/minicondanew/lib/python3.11/logging/__init__.py", line 978, in handle
    self.emit(record)
  File "/home/omk/minicondanew/lib/python3.11/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg)
Exception: Command '/bin/bash /mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align18/nextDenovoDupAll.sh > /mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align18/nextDenovoDupAll.sh.o 2> /mnt/gcfgrandmaison/T07_sesu/out_nextden/01_rundir/01.raw_align/03.raw_align.sh.work/raw_align18/nextDenovoDupAll.sh.e' returned non-zero exit status 1, error info: .


^C[34267 WARNING] 2024-07-08 09:30:20 Accepted a killed signal and killing all running jobs, please wait...
[34267 WARNING] 2024-07-08 09:30:20 Killed all running jobs done
[34267 WARNING] 2024-07-08 09:30:20 Exit!
Exception ignored in: <module 'threading' from '/home/omk/minicondanew/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/home/omk/minicondanew/lib/python3.11/threading.py", line 1552, in _shutdown
    for atexit_call in reversed(_threading_atexits):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/omk/minicondanew/lib/python3.11/site-packages/paralleltask/task_control.py", line 333, in clean
    self._clean()
  File "/home/omk/minicondanew/lib/python3.11/site-packages/paralleltask/task_control.py", line 394, in _clean
    sys.exit(1)
SystemExit: 1

```

**Comment by moold** [comment]
I suggest filtering the input data and only using the longest 60x data as input for assembly.
