### ISSUE TITLE
raw_align failed，return non-zero exit status 137

### ISSUE THREAD

**Issue by aqgy-zj** [Nextomics/NextDenovo#220]
**Describe the bug**
raw_align failed，return non-zero exit status 137 （I have referred to the issue #151 and issue #5）

**Error message**
[3797 CRITICAL] 2024-12-04 12:11:24 Command '/bin/bash /media/yc/NewqSSD/feishajiyin/ont/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align1/nextDenovo.sh > /media/yc/NewqSSD/feishajiyin/ont/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align1/nextDenovo.sh.o 2> /media/yc/NewqSSD/feishajiyin/ont/01_rundir/01.raw_align/02.raw_align.sh.work/raw_align1/nextDenovo.sh.e' returned non-zero exit status 137, error info: 
Traceback (most recent call last):
  File "/home/yc/Downloads/NextDenovo/nextDenovo", line 857, in <module>
    main(args)
  File "/home/yc/Downloads/NextDenovo/nextDenovo", line 651, in main
    task.run.start()
  File "/home/yc/shengxin/lib/python3.12/site-packages/paralleltask/task_control.py", line 350, in start
    self._start()
  File "/home/yc/shengxin/lib/python3.12/site-packages/paralleltask/task_control.py", line 376, in _start
    self.submit(job)
  File "/home/yc/shengxin/lib/python3.12/site-packages/paralleltask/task_control.py", line 254, in submit
    _, stdout, _ = self.run(job.cmd)
                   ^^^^^^^^^^^^^^^^^
  File "/home/yc/shengxin/lib/python3.12/site-packages/paralleltask/task_control.py", line 294, in run
    log.critical("Command '%s' returned non-zero exit status %d, error info: %s." % (cmd, p.returncode, stderr))
  File "/usr/lib/python3.12/logging/__init__.py", line 1586, in critical
    self._log(CRITICAL, msg, args, **kwargs)
  File "/usr/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
  File "/home/yc/shengxin/lib/python3.12/site-packages/paralleltask/kit.py", line 42, in emit
    raise Exception(record.msg
**Genome characteristics**
genome size 220mb

**Input data**
ONT  61G
General summary:    （nanoplot）    
Mean read length:                104,391.1
Mean read quality:                    11.3
Median read length:               96,973.0
Median read quality:                  12.0
Number of reads:                 312,929.0
Read length N50:                 100,651.0
STDEV read length:                24,474.3
Total bases:              32,667,001,144.0
Number, percentage and megabases of reads above quality cutoffs
>Q10:	249548 (79.7%) 26029.7Mb
>Q15:	14418 (4.6%) 1487.0Mb
>Q20:	4 (0.0%) 0.6Mb
>Q25:	0 (0.0%) 0.0Mb
>Q30:	0 (0.0%) 0.0Mb
Top 5 highest mean basecall quality scores and their read lengths
1:	24.2 (155770)
2:	20.5 (183072)
3:	20.5 (91443)
4:	20.3 (125423)
5:	19.6 (155211)
Top 5 longest reads and their mean basecall quality score
1:	623204 (11.0)
2:	595329 (11.9)
3:	571864 (15.9)
4:	481047 (10.7)
5:	467645 (11.6)

**Config file**
Some values of paramers have been given by the paper. They are given below:
genome size = 220mb
read cutoff =50000
seed cutoff=55959
seed depth=45

[General]
job_type = local # local, slurm, sge, pbs, lsf
job_prefix = nextDenovo
task = all # all, correct, assemble
rewrite = yes # yes/no
deltmp = yes 
parallel_jobs = 1 # number of tasks used to run in parallel
input_type = raw # raw, corrected
read_type = ont # clr, ont, hifi
input_fofn = input.fofn
workdir = 01_rundir

[correct_option]
read_cutoff = 50k 
genome_size = 220m # estimated genome size
seed_cutoff=55959
sort_options = -m 3g -t 10 
minimap2_options_raw =  -x ava-ont -t 8
pa_correction = 1 # number of corrected tasks used to run in parallel, each corrected task requires ~TOTAL_INPUT_BASES/4 bytes of memory usage.
correction_options = -p 10
blocksize=1g

[assemble_option]
minimap2_options_cns = -t 5 -x ava-ont -k 21 -w 21 
nextgraph_options = -a 1

[correct_option]
read_cutoff = 50k
genome_size = 220m # estimated genome size
seed_cutoff=55959
sort_options = -m 3g -t 10 
minimap2_options_raw =  -x ava-ont -t 8
pa_correction = 1 # number of corrected tasks used to run in parallel, each corrected task requires ~TOTAL_INPUT_BASES/4 bytes of memory usage.
correction_options = -p 10
blocksize=1g

[assemble_option]
minimap2_options_cns = -t 5 -x ava-ont -k 21 -w 21 
nextgraph_options = -a 1

**Operating system**
Ubuntu 24.04.1 LTS.

**GCC**
13.2.0.

**Python**
3.12.3

**NextDenovo**
2.5.2

**Additional context** (Optional)
I use Vmware to install the ubuntu system in a windows system.
The ubuntu system has 32g of memory , 1CPU with 20 cores. (same to the windows system)
The memory that has been used is 8gb when the program is running.

**Comment by moold** [comment]
The RAM is not enough, you should try nextDenovo with another computer with >=256Gb RAM.

**Comment by aqgy-zj** [comment]
DIY a computer with 256GB RAM or cloud computer with 500GB RAM.
thank you !




忧桑的coding
***@***.***

&nbsp;

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Nextomics/NextDenovo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年12月13日(星期五) 下午3:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Nextomics/NextDenovo] raw_align failed，return non-zero exit status 137 (Issue #220)





 
The RAM is not enough, you should try nextDenovo with another computer with &gt;=256Gb RAM.
