### ISSUE TITLE
an unknown error

### ISSUE THREAD

**Issue by yangzhuang0916** [Nextomics/NextDenovo#92]
Dear Dr Hu，

        I uses NextDevono to assembly my genome, the size is about 700M. My data id PacBio data. But i meet a error, as follow.
        So i need your help. Thank you in advance.

Traceback (most recent call last):
  File "/public/home/software/opt/bio/software/NextDenovo/2.3.0//nextDenovo", line 748, in <module>
    main(args)
  File "/public/home/software/opt/bio/software/NextDenovo/2.3.0//nextDenovo", line 488, in main
    cfg = ConfigParser(args[1][0]).cfg
  File "/public/home/software/opt/bio/software/NextDenovo/2.3.0/lib/config_parser.py", line 14, in __init__
    self._check()
  File "/public/home/software/opt/bio/software/NextDenovo/2.3.0/lib/config_parser.py", line 89, in _check
    self.cfg['seed_cutoff'] = str(parse_num_unit(self.cfg['seed_cutoff']))
  File "/public/home/software/opt/bio/software/NextDenovo/2.3.0/lib/kit.py", line 121, in parse_num_unit
    return int(value * unit + .499)
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'

**Comment by moold** [comment]
Please provide more details, refer [here](https://github.com/Nextomics/NextDenovo/issues/new?assignees=&labels=&template=bug-or-error-report.md&title=)

**Comment by tinyhys** [comment]
您是否使用了2.4版的自动调用seq_stat? 我使用之后也出现了 TypeError: unsupported operand type(s) for *: 'float' and 'NoneType' 的错误, 但是上面的报错内容好像不同, 可能是输入的值导致计算结果出现了小数程序不识别, 后来还是自己定义个整数的seed_cutsoff就可以了. 其实我一直不太理解这里的seed是指的什么, seed depth就用默认的45了
